export const emisorasData = [
  {
    id: 1,
    image: require('../assets/emisorasPortadas/activaFm.webp'),
    background: require('../assets/backgrounds/activa-back.jpg'),
    banner: require('../assets/banners/ACTIVAFM.jpg'),
    title: 'Activa FM',
    description: 'LA MEJOR COMBINACIÓN DE ÉXITOS',
    color: '#e73b3c',
  },
  {
    id: 4,
    image: require('../assets/emisorasPortadas/bikini.webp'),
    background: require('../assets/backgrounds/bikini-back.jpg'),
    banner: require('../assets/banners/BIKINI.jpg'),
    title: 'Bikini FM',
    description: 'LA RADIO DEL REMEMBER',
    color: '#66ccff',
  },
  {
    id: 96,
    image: require('../assets/emisorasPortadas/comboi.webp'),
    background: require('../assets/backgrounds/comboi-back.jpg'),
    banner: require('../assets/banners/COMBOI.jpg'),
    title: 'Comboi FM',
    description: 'LA RADIO DE LA TERRETA',
    color: '#ffffff',
  },
  {
    id: 76,
    image: require('../assets/emisorasPortadas/corazonFm.webp'),
    background: require('../assets/backgrounds/corazon-back.jpg'),
    banner: require('../assets/banners/CORAZON.jpg'),
    title: 'Corazon FM',
    description: 'LA MÚSICA QUE TE ENAMORA',
    color: '#ffffff',
  },
  {
    id: 5,
    image: require('../assets/emisorasPortadas/esencia.webp'),
    background: require('../assets/backgrounds/esencia-back.jpg'),
    banner: require('../assets/banners/ESENCIA.jpg'),
    title: 'Esencia FM',
    description: 'LA ESENCIA DE NUESTRA MÚSICA',
    color: '#ff3366',
  },
  {
    id: 6,
    image: require('../assets/emisorasPortadas/goldFm.webp'),
    background: require('../assets/backgrounds/gold-back.jpg'),
    banner: require('../assets/banners/GOLD.jpg'),
    title: 'Gold FM',
    description: 'LA MÚSICA DE TU VIDA',
    color: '#ffffff',
  },
  {
    id: 8,
    image: require('../assets/emisorasPortadas/laFlamenca.webp'),
    background: require('../assets/backgrounds/flamenca-back.jpg'),
    banner: require('../assets/banners/FLAMENCA.jpg'),
    title: 'La Flamenca',
    description: '¡FLAMENCO Y OLÉ!',
    color: '#33cc33',
  },
  {
    id: 14,
    image: require('../assets/emisorasPortadas/laIndie.webp'),
    background: require('../assets/backgrounds/indie-back.jpg'),
    banner: require('../assets/banners/INDIE.jpg'),
    title: 'La Indie',
    description: 'LA EMISORA QUE POCOS ENTIENDEN',
    color: '#403437',
  },
  {
    id: 3,
    image: require('../assets/emisorasPortadas/laMega.webp'),
    background: require('../assets/backgrounds/mega-back.jpg'),
    banner: require('../assets/banners/MEGA.jpg'),
    title: 'La Mega',
    description: '¡SÓLO BAILAMOS!',
    color: '#9900cc',
  },
  {
    id: 9,
    image: require('../assets/emisorasPortadas/laQueSuena.webp'),
    background: require('../assets/backgrounds/laquesuena-back.jpg'),
    banner: require('../assets/banners/LAQUESUENA.jpg'),
    title: 'La Que Suena',
    description: '¡PARA QUE NO PARES!',
    color: '#afc435',
  },
  {
    id: 12,
    image: require('../assets/emisorasPortadas/masActiva.webp'),
    background: require('../assets/backgrounds/+activa-back.jpg'),
    banner: require('../assets/banners/+ACTIVA.jpg'),
    title: 'Mas Activa',
    description: 'LA MEJOR COMBINACIÓN DE ÉXITOS DE AYER Y HOY',
    color: '#e73b3c',
  },
  {
    id: 2,
    image: require('../assets/emisorasPortadas/muyBuena.webp'),
    background: require('../assets/backgrounds/mb-back.jpg'),
    banner: require('../assets/banners/LAQUESUENA.jpg'),
    title: 'Muy Buena',
    description: '¡QUE BIEN SUENA!',
    color: '#ffcb03',
  },
  {
    id: 86,
    image: require('../assets/emisorasPortadas/radioHallo.webp'),
    background: require('../assets/backgrounds/hallo-back.jpg'),
    banner: require('../assets/banners/HALLO-2.jpg'),
    title: 'Radio Hallo',
    description: 'MUSIK, NACHRICHTEN UND VIELES MEHR',
    color: '#ffffff',
  },
  {
    id: 7,
    image: require('../assets/emisorasPortadas/rockstar.webp'),
    background: require('../assets/backgrounds/rockstar-back.jpg'),
    banner: require('../assets/banners/ROCKSTAR.jpg'),
    title: 'Rockstar',
    description: 'LA RADIO DE LAS ESTRELLAS DE ROCK',
    color: '#cccccc',
  },
  {
    id: 95,
    image: require('../assets/emisorasPortadas/solLatino.webp'),
    background: require('../assets/backgrounds/latino-back.jpg'),
    banner: require('../assets/banners/SOL-LATINO.jpg'),
    title: 'Sol Latino',
    description: 'NÚMERO 1 EN SALSA, MERENGUE Y MÁS',
    color: '#fecc03',
  },
];
