export const emisorasData = [
  {
    id: 1,
    image: require('../assets/emisorasPortadas/activaFm.webp'),
    background: require('../assets/backgrounds/activa-back.jpg'),
    title: 'Activa FM',
    description: 'descripcion de la emisora',
    color: '#e73b3c',
  },
  {
    id: 4,
    image: require('../assets/emisorasPortadas/bikini.webp'),
    background: require('../assets/backgrounds/bikini-back.jpg'),
    title: 'Bikini FM',
    description: 'descripcion de la emisora',
    color: '#66ccff',
  },
  {
    id: 96,
    image: require('../assets/emisorasPortadas/comboi.webp'),
    background: require('../assets/backgrounds/comboi-back.jpg'),
    title: 'Comboi FM',
    description: 'descripcion de la emisora',
    color: '#ffffff',
  },
  {
    id: 76,
    image: require('../assets/emisorasPortadas/corazonFm.webp'),
    background: require('../assets/backgrounds/corazon-back.jpg'),
    title: 'Corazon FM',
    description: 'descripcion de la emisora',
    color: '#ffffff',
  },
  {
    id: 5,
    image: require('../assets/emisorasPortadas/esencia.webp'),
    background: require('../assets/backgrounds/esencia-back.jpg'),
    title: 'Esencia FM',
    description: 'descripcion de la emisora',
    color: '#ff3366',
  },
  {
    id: 6,
    image: require('../assets/emisorasPortadas/goldFm.webp'),
    background: require('../assets/backgrounds/gold-back.jpg'),
    title: 'Gold FM',
    description: 'descripcion de la emisora',
    color: '#ffffff',
  },
  {
    id: 8,
    image: require('../assets/emisorasPortadas/laFlamenca.webp'),
    background: require('../assets/backgrounds/flamenca-back.jpg'),
    title: 'La Flamenca',
    description: 'descripcion de la emisora',
    color: '#33cc33',
  },
  {
    id: 14,
    image: require('../assets/emisorasPortadas/laIndie.webp'),
    background: require('../assets/backgrounds/indie-back.jpg'),
    title: 'La Indie',
    description: 'descripcion de la emisora',
    color: '#403437',
  },
  {
    id: 3,
    image: require('../assets/emisorasPortadas/laMega.webp'),
    background: require('../assets/backgrounds/mega-back.jpg'),
    title: 'La Mega',
    description: 'descripcion de la emisora',
    color: '#9900cc',
  },
  {
    id: 9,
    image: require('../assets/emisorasPortadas/laQueSuena.webp'),
    background: require('../assets/backgrounds/laquesuena-back.jpg'),
    title: 'La Que Suena',
    description: 'descripcion de la emisora',
    color: '#afc435',
  },
  {
    id: 12,
    image: require('../assets/emisorasPortadas/masActiva.webp'),
    background: require('../assets/backgrounds/+activa-back.jpg'),
    title: 'Mas Activa',
    description: 'descripcion de la emisora',
    color: '#e73b3c',
  },
  {
    id: 2,
    image: require('../assets/emisorasPortadas/muyBuena.webp'),
    background: require('../assets/backgrounds/mb-back.jpg'),
    title: 'Muy Buena',
    description: 'descripcion de la emisora',
    color: '#ffcb03',
  },
  {
    id: 86,
    image: require('../assets/emisorasPortadas/radioHallo.webp'),
    background: require('../assets/backgrounds/hallo-back.jpg'),
    title: 'Radio Hallo',
    description: 'descripcion de la emisora',
    color: '#ffffff',
  },
  {
    id: 7,
    image: require('../assets/emisorasPortadas/rockstar.webp'),
    background: require('../assets/backgrounds/rockstar-back.jpg'),
    title: 'Rockstar',
    description: 'descripcion de la emisora',
    color: '#cccccc',
  },
  {
    id: 95,
    image: require('../assets/emisorasPortadas/solLatino.webp'),
    background: require('../assets/backgrounds/latino-back.jpg'),
    title: 'Sol Latino',
    description: 'descripcion de la emisora',
    color: '#fecc03',
  },
];
